spring:
  application:
    name: url-shortener
    
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update # For dev. Use validate in production.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

app:
  domain: "http://localhost:8080/"
  security:
    safe-browsing:
      api-key: ${SAFE_BROWSING_API_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0 # 100% trace sampling for dev. Decrease in production.
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans"